export const CHANGE_LOADING = 'CHANGE_LOADING';
export const CHANGE_LIST_ARTICLE = 'CHANGE_LIST_ARTICLE';
export const SET_SQLITE = 'SET_SQLITE';
export const CHANGE_LIST_JOKE = 'CHANGE_LIST_JOKE';
export const CHANGE_LIST_CATE = 'CHANGE_LIST_CATE';